name: Louper
 
web: [http://github.com/creaven/Louper/](http://github.com/creaven/Louper/)
 
description: zoom image using real loupe
 
authors: [Anton Samoylov](http://mifjs.net.net)
 
license: MIT License
 
copyright: &copy; [Anton Samoylov](http://mifjs.net)
 
author: magmoro
 
category: Effects
 
tags: [image, zoom]
 
sources:
  - "Source/Louper.js"

demo: http://mifjs.net/misc/louper/Demo/

current: 1.1


